#include "vertexData.h"

const D3D11_INPUT_ELEMENT_DESC PosTexIndex::inputLayout[3] =
{
// Î»ÖÃ×Ö¶Î
{ "POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0 },
// ÎÆÀí×ø±ê×Ö¶Î
{ "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0, D3D11_APPEND_ALIGNED_ELEMENT, D3D11_INPUT_PER_VERTEX_DATA, 0 },
// ÎÆÀíË÷Òý×Ö¶Î
{ "TEXINDEX", 0, DXGI_FORMAT_R32_FLOAT, 0, D3D11_APPEND_ALIGNED_ELEMENT, D3D11_INPUT_PER_VERTEX_DATA, 0 }
};