#pragma once

// 定义映射表中使用的宏
#define CALCULATOR_SHIELD_HP_MAX 1
#define CALCULATOR_ARMOR_HP_MAX 2
#define CALCULATOR_STRUCTURE_HP_MAX 3
#define CALCULATOR_EM_DAMAGE 4
#define CALCULATOR_EXPLOSIVE_DAMAGE 5
#define CALCULATOR_KINETIC_DAMAGE 6
#define CALCULATOR_THERMAL_DAMAGE 7

// 可以根据需要添加更多的宏定义