#pragma once
#define ATTR_ID_ITEM_DMG 3  // 物品损坏
#define ATTR_ID_ITEM_MASS 4  // 质量
#define ATTR_ID_CAPACITOR_NEED 6  // 启用耗电量
#define ATTR_ID_STRUCTURE_VALUE 9  // 结构值
#define ATTR_ID_POWER_OUTPUT 11  // 能量栅格输出
#define ATTR_ID_LOW_SLOTS 12  // 低能量槽
#define ATTR_ID_MED_SLOTS 13  // 中能量槽
#define ATTR_ID_HI_SLOTS 14  // 高能量槽
#define ATTR_ID_POWER_LOAD 15  // 能量负荷
#define ATTR_ID_POWER 30  //能量栅格占用
#define ATTR_ID_WARP_FACTOR 21  //
#define ATTR_ID_MAX_VELOCITY 37  // 最大速度
#define ATTR_ID_CAPACITY 38  // 容量
#define ATTR_ID_SLOTS 47  // 槽位
#define ATTR_ID_CPU_OUTPUT 48  // CPU输出
#define ATTR_ID_CPU_LOAD 49  // CPU载荷
#define ATTR_ID_CPU 50  // CPU使用量
#define ATTR_ID_MAX_RANGE 54  // 最佳射程
#define ATTR_ID_RECHARGE_RATE 55  // 电容回充时间
#define ATTR_ID_AGILITY 70  // 惯性调整
#define ATTR_ID_SHIELD_HP_BONUS 72 //护盾值加值
#define ATTR_ID_DURATION 73  // 作用时间/单次运转时间
#define ATTR_ID_MAX_TARGET_RANGE 76  // 锁定范围上限
#define ATTR_ID_MINING_AMOUNT 77  //开采量
#define ATTR_ID_SCAN_SPEED 79  //
#define ATTR_ID_LAUNCHER_SLOTS_LEFT 101  // 发射器安装数
#define ATTR_ID_TURRET_SLOTS_LEFT 102  // 炮台安装数
#define ATTR_ID_KINETIC_DAMAGE_RESONANCE 109  // 结构动能伤害抗性
#define ATTR_ID_THERMAL_DAMAGE_RESONANCE 110  // 结构热能伤害抗性
#define ATTR_ID_EXPLOSIVE_DAMAGE_RESONANCE 111  // 结构爆炸伤害抗性
#define ATTR_ID_EM_DAMAGE_RESONANCE 113  // 结构电磁伤害抗性
#define ATTR_ID_MAIN_COLOR 124  //
#define ATTR_ID_MAX_PASSENGERS 129  // 最大乘客数
#define ATTR_ID_UNIFORMITY 136  //
#define ATTR_ID_WARP_CAPACITOR_NEED 153  //
#define ATTR_ID_VOLUME 161  // 体积
#define ATTR_ID_RADIUS 162  // 半径
#define ATTR_ID_REQUIRED_SKILL1 182  // 主技能需求
#define ATTR_ID_CARGO_SCAN_RESISTANCE 188  // 货物扫描抗性
#define ATTR_ID_MAX_LOCKED_TARGETS 192  // 目标锁定数上限加成
#define ATTR_ID_SCAN_RADAR_STRENGTH 208  // 雷达感应强度
#define ATTR_ID_SCAN_LADAR_STRENGTH 209  // 光雷达感应强度
#define ATTR_ID_SCAN_MAGNETOMETRIC_STRENGTH 210  // 磁力感应强度
#define ATTR_ID_SCAN_GRAVIMETRIC_STRENGTH 211  // 引力感应强度
#define ATTR_ID_PROPULSION_GRAPHIC_ID 217  //
#define ATTR_ID_GFX_BOOSTER_ID 246  //
#define ATTR_ID_SHIELD_CAPACITY 263  // 护盾容量
#define ATTR_ID_ARMOR_HP 265  // 装甲值
#define ATTR_ID_ARMOR_EM_DAMAGE_RESONANCE 267  // 装甲电磁伤害抗性
#define ATTR_ID_ARMOR_EXPLOSIVE_DAMAGE_RESONANCE 268  // 装甲爆炸伤害抗性
#define ATTR_ID_ARMOR_KINETIC_DAMAGE_RESONANCE 269  // 装甲动能伤害抗性
#define ATTR_ID_ARMOR_THERMAL_DAMAGE_RESONANCE 270  // 装甲热能伤害抗性
#define ATTR_ID_SHIELD_EM_DAMAGE_RESONANCE 271  // 护盾电磁伤害抗性
#define ATTR_ID_SHIELD_EXPLOSIVE_DAMAGE_RESONANCE 272  // 护盾爆炸伤害抗性
#define ATTR_ID_SHIELD_KINETIC_DAMAGE_RESONANCE 273  // 护盾动能伤害抗性
#define ATTR_ID_SHIELD_THERMAL_DAMAGE_RESONANCE 274  // 护盾热能伤害抗性
#define ATTR_ID_REQUIRED_SKILL1_LEVEL 277  //技能需求等级
#define ATTR_ID_DRONE_CAPACITY 283  // 无人机容量
#define ATTR_ID_TECH_LEVEL 422  // 科技等级
#define ATTR_ID_SHIELD_RECHARGE_RATE 479  // 护盾回充时间
#define ATTR_ID_CAPACITOR_CAPACITY 482  // 电容容量
#define ATTR_ID_SHIELD_UNIFORMITY 484  //
#define ATTR_ID_SHIP_BONUS_CC 487  //
#define ATTR_ID_ARMOR_UNIFORMITY 524  //
#define ATTR_ID_STRUCTURE_UNIFORMITY 525  //
#define ATTR_ID_SIGNATURE_RADIUS 552  // 信号半径
#define ATTR_ID_SCAN_RESOLUTION 564  // 扫描分辨率
#define ATTR_ID_WARP_SPEED_MULTIPLIER 600  // 跃迁速度倍增系数
#define ATTR_ID_META_LEVEL_OLD 633  // 衍生等级
#define ATTR_ID_SHIP_BONUS_CC2 657  //
#define ATTR_ID_MAX_DIRECTIONAL_VELOCITY 661  //
#define ATTR_ID_MIN_TARGET_VEL_DMG_MULTIPLIER 662  //
#define ATTR_ID_QUANTITY 805  // 数量
#define ATTR_ID_HULL_EM_DAMAGE_RESONANCE 974  // 结构电磁伤害抗性（船体相关）
#define ATTR_ID_HULL_EXPLOSIVE_DAMAGE_RESONANCE 975  // 结构爆炸伤害抗性（船体相关）
#define ATTR_ID_HULL_KINETIC_DAMAGE_RESONANCE 976  // 结构动能伤害抗性（船体相关）
#define ATTR_ID_HULL_THERMAL_DAMAGE_RESONANCE 977  // 结构热能伤害抗性（船体相关）
#define ATTR_ID_UPGRADE_CAPACITY 1132  // 校准值
#define ATTR_ID_RIG_SLOTS 1137  // 改装件安装座
#define ATTR_ID_UPGRADE_SLOTS_LEFT 1154  // 改装件槽位
#define ATTR_ID_ARMOR_HP_BONUS 1159  //装甲值加成
#define ATTR_ID_HEAT_CAPACITY_HI 1178  // 高热量容量
#define ATTR_ID_HEAT_DISSIPATION_RATE_HI 1179  // 高热量发散率
#define ATTR_ID_HEAT_DISSIPATION_RATE_MED 1196  // 中热量发散率
#define ATTR_ID_HEAT_DISSIPATION_RATE_LOW 1198  // 低热量发散率
#define ATTR_ID_HEAT_CAPACITY_MED 1199  // 中热量容量
#define ATTR_ID_HEAT_CAPACITY_LOW 1200  // 低热量容量
#define ATTR_ID_HEAT_GENERATION_MULTIPLIER 1224  // 热量生成倍增系数
#define ATTR_ID_HEAT_ATTENUATION_HI 1259  // 高热量发散（衰减相关）
#define ATTR_ID_HEAT_ATTENUATION_MED 1261  // 中热量发散（衰减相关）
#define ATTR_ID_HEAT_ATTENUATION_LOW 1262  // 低热量发散（衰减相关）
#define ATTR_ID_DRONE_BANDWIDTH 1271  // 无人机带宽
#define ATTR_ID_BASE_WARP_SPEED 1281  // 舰船跃迁速度
#define ATTR_ID_RIG_SIZE 1547  // 改装件尺寸
#define ATTR_ID_FW_LP_KILL 1555  //
#define ATTR_ID_TYPE_COLOR_SCHEME 1768  //
#define ATTR_ID_ENERGY_WARFARE_RESISTANCE 2045  // 电容战抗性
#define ATTR_ID_WEAPON_DISRUPTION_RESISTANCE 2113  // 武器干扰抗性
#define ATTR_ID_STASIS_WEBIFIER_RESISTANCE 2115  // 停滞缠绕抗性
#define ATTR_ID_RESIDUE_VOLUME_MULTIPLIER 3153  // 采矿浪费倍率Residue Volume Multiplier
#define ATTR_ID_RESIDUE_PROBABILITY 3154// 采矿浪费几率
#define ATTR_ID_CURRENT_HP 5000
#define ATTR_ID_CURRENT_ARMOR 5001
#define ATTR_ID_CURRENT_SHIELD 5002