#pragma once
#define CONTAINER_TYPE_CARGO 0
#define CONTAINER_TYPE_DRONE_POD 1
#define CONTAINER_TYPE_EQUIPMENT_SLOT 2
#define CONTAINER_TYPE_AMMUNITION_STORAGE 3
#define CONTAINER_TYPE_FRIGATE_ESCAPE_POD 4
#define CONTAINER_TYPE_FUEL_TANK 5
#define CONTAINER_TYPE_ORE_STORAGE 6
#define CONTAINER_TYPE_MINERAL_STORAGE 7
#define CONTAINER_TYPE_PILOT_STORAGE 8

#define CONTAINER_TYPE_HIGH_SLOT 9
#define CONTAINER_TYPE_MEDIUM_SLOT 10
#define CONTAINER_TYPE_LOW_SLOT 11
#define CONTAINER_TYPE_RIG_SLOT 12
